### ISSUE TITLE
How to get Simkl plugin on Jellyfin?

### ISSUE THREAD

**Issue by zohaibs1011** [SIMKL/Emby#12]
I put the dll file in a folder in the plugins section and restarted server yet no affect.

Thanks

**Comment by Deanosim** [comment]
It would need to be forked and converted to work with Jellyfin.

**Comment by marine1988** [comment]
! more waiting for Jellyfin version since trakt is working very bad!

**Comment by masyk** [comment]
https://simkl.com/apps/jellyfin/
