### ISSUE TITLE
The plugin does not work on Android server

### ISSUE THREAD

**Issue by RTrampov** [SIMKL/Emby#13]
Hi, I recently started using Emby Android server on Nvidia Shield Pro 2019 and the Simkl plugin doesn't seem to work.

It happens for both movies and TV shows - the attached logs are from a TV show but it always fails with the same error:
```
Caught unknown exception while trying to scrobble: Method not found: System.Collections.Generic.Dictionary`2<string, string> MediaBrowser.Model.Dto.BaseItemDto.get_ProviderIds()
```

I am using the latest released (at the time of submitting this issue) version of [Emby server for Android](https://emby.media/server-android.html) - 4.5.4.0. Let me know if additional information is needed.

[debug_log.txt](https://github.com/SIMKL/Emby/files/6217495/debug_log.txt)

**Comment by husky-cmd** [comment]
fixed, soon will be updated in emby catalog

**Comment by ekleop** [comment]
thanks, soon will be updated in emby catalog
