### ISSUE TITLE
Plugin Settings emtpy

### ISSUE THREAD

**Issue by Oratorian** [SIMKL/Emby#16]
I installed Simkl for emby version 1.0.6.0, when i go to the plugin settings, the dropdownbox is empty.

Running emby 4.8.0.66

I noticed the following in my log file

https://‌‍‍127.0.0.1:8096/emby/web/configurationpages?PageType=PluginConfiguration&UserId=19b71ac3eea04682b9f8c497f4d7c4ca&EnableInUserMenu=false&X-Emby-Client=Emby Web&X-Emby-Device-Name=Brave Windows&X-Emby-Device-Id=2743ae81-4870-41c9-ab2d-321b2f1f69b7&X-Emby-Client-Version=4.8.0.66&X-Emby-Token=‌&X-Emby-Language=de

It says EnableInUserMenu=false

But i can't find any user setting to enable it.

**Comment by Adam-Homf** [comment]
same with 1.0.6,, running emby 4.8.0.78 on qnap

**Comment by drashna** [comment]
Is still an issue on 4.8.0.80 (release), and 4.8.1.0 (release). 

These are non-beta builds, so likely going to see a more people running into this.

**Comment by Adam-Homf** [comment]
Also an issue still on 4.9.0.1 (beta)

**Comment by ekleop** [comment]
updated the plugin to 1.0.7 version
check the catalog

**Comment by Adam-Homf** [comment]
It works, confirmed on 4.9.0.1, thank you!

**Comment by drashna** [comment]
Can confirm that it works on 4.8.1.0, as well.
