### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by zluckytraveler** [SIMKL/Emby#17]
Unable to login when selecting user, and receiving an error.

`Some error occurred see browser log for more details`

Upon checking the logs, the only thing it shows is an issue for a completely different user.
`2024-10-14 13:00:50.125 Error Simkl Scrobbler: Can't scrobble: User mrwxxxxxx@gmail.com not logged in (True)`

https://github.com/user-attachments/assets/00a17a3e-1c20-4194-bf12-15be2b967b65

**Comment by Simkl-dev** [comment]
On Emby's dashboard, scroll to the bottom and, on expert options, select "Logs" (right above "Notifications")
Click on "Enable debug logging"
Restart the server and reproduce the error

**Comment by zluckytraveler** [comment]
@Simkl-dev 
Just so you know that guided pathway is outdated. 
It is now `Settings > Logs > Settings (Tab) > Enable Debug Logging > Yes`

With debug logging these are the only other errors besides checking for users not logged in.
```
2024-10-14 13:29:58.128 Error Simkl Scrobbler: No object: Object reference not set to an instance of an object.
2024-10-14 13:29:58.128 Error Simkl Scrobbler:    at Simkl.Services.Scrobbler.embyPlaybackProgress(Object sessions, PlaybackProgressEventArgs e)```

**Comment by Simkl-dev** [comment]
You were installing the plugin from the emby.media  https website. Which was trying to open your http local emby server. 
![image](https://github.com/user-attachments/assets/72c0a035-f565-44ca-aba1-365ddb666334) which is not allowed by browsers. Opening your dashboard from your local server 172.*** allows to install the plugin without browser errors.

Configuring your server with https:// allows you to user emby.media website to connect to your https server. Alternative is to just open your emby dashboard directy from your local server to set up plugins.
