### ISSUE TITLE
Failing to scrobble full paths

### ISSUE THREAD

**Issue by daviddavo** [SIMKL/Emby#5]
Error log from @ekleop 
![image](https://user-images.githubusercontent.com/10263941/62711229-efefaa00-b9f8-11e9-93cc-f80441ce02f2.png)

Reproduction of the API responses using curl
![image](https://user-images.githubusercontent.com/10263941/62711285-101f6900-b9f9-11e9-8e62-dfce42dc0a89.png)

**Comment by daviddavo** [comment]
Now it retries using only filename

**Comment by ekleop** [comment]
if it returns an empty "show" type again it should skip the results of the api and doesn't do anything. It means we cannot detect corresponding episode or detected it as wrong TV Show. This situation can occur with filenames too
